config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  #Admin stuff
  namespace :admin  do
    resources :payloads do
      collection do
        get 'completed'
      end
    end
    resources :users
  end

  resources :payloads
  resource :admin
  resource :home
  resource :external
  root to: "externals#show"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/payload.rb
class Payload < ApplicationRecord
  mount_uploader :file, PayloadUploader

  validates_presence_of :uuid, :owner_email

  after_initialize :generate_uuid
  after_create :deliver

  scope(:completed, -> { where "payloads.uploaded_at IS NOT NULL" })

  def deliver
    PayloadMailer.with(:payload => self).notification.deliver_now
  end


  def incomplete?
    not(self.complete?)
  end
  
  def complete?
    self.uploaded_at.present?
  end

  class << self
    def seek(id, raise_error = true)
      raise(ActiveRecord::RecordNotFound, "Cannot find/seek/search without an id (or uuid)") if raise_error && id.blank?

      if id.to_s.is_i?
        self.find(id)
      else
        self.where(:uuid => id).first
      end
    end
  end

  ############################################################################
  protected
  ############################################################################

  def generate_uuid
    self.uuid ||= loop do
      random_uuid = SecureRandom.uuid.gsub("-","").slice(0,24)
      break random_uuid unless self.class.exists?(uuid: random_uuid)
    end
  end

end

app/models/user.rb
class User < ApplicationRecord

  validates_presence_of :first_name, :last_name, :email, :admin_level

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable


  def name
    "#{self.first_name} #{self.last_name}".strip
  end

  def is_admin?
    @is_admin ||= self.admin_level > 0
  end

  def access_level
    if self.is_admin?
      "Admin"
    else
      "Regular"
    end
  end
end

app/controllers/admin/payloads_controller.rb
class Admin::PayloadsController < AdminController

  def index
    @payloads = Payload.paginate(:page => params[:page])
  end

  def new
    @payload = Payload.new
    render :action => :action
  end

  def create
    @payload  = Payload.new payload_params
    begin
      @payload.save!
      flash[:success] = "New Payload Created"
      redirect_to admin_payloads_path
    rescue Exception => error
      flash[:error] = error.message
      render :action => :action
    end
  end


  def completed
    @payloads = Payload.completed.paginate(:page => params[:page])
    render :action => :index
  end


  ############################################################################
  private
  ############################################################################

  def payload_params
    params.require(:payload).permit(:owner_email, :user_id)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController


  def index
    @users = User.paginate(:page => params[:page])
  end

  def new
    @user = User.new
    render :action => :action
  end


  def create
    @user  = User.new user_params
    begin
      @user.save!
      flash[:success] = "New User Created"
      redirect_to admin_users_path
    rescue Exception => error
      flash[:error] = error.message
      render :action => :action
    end
  end


  def show
    @user = User.find(params[:id])
    redirect_to edit_admin_user_path(@user)
  end

  def edit
    @user = User.find(params[:id])
    render :action => :action
  end


  def update
    @user = User.find(params[:id])
    begin
      @user.update_attributes! user_params
      flash[:success] = "User Created"
      redirect_to admin_users_path
    rescue Exception => error
      flash[:error] = error.message
      render :action => :action
    end
  end

  ############################################################################
  private
  ############################################################################

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :admin_level, :password, :password_confirmation)
  end



end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  layout "admin"
end

app/controllers/admins_controller.rb
class AdminsController < AdminController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_in_path_for(resource)
    if resource.admin_level > 0
      "/admin"
    else
      home_path
    end
  end

end

app/controllers/externals_controller.rb
class ExternalsController < ApplicationController
  before_action :check_signed_in

  def check_signed_in
    redirect_to after_sign_in_path_for(current_user) if signed_in?
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/payloads_controller.rb
class PayloadsController < ApplicationController
  before_action :seek_payload

  def show
    redirect_to edit_payload_path(params[:id]) and return if @payload.incomplete?
  end


  def edit
  end

  def update
    begin
      @payload.update_attributes! payload_params
      flash[:success] = "payload Created"
      redirect_to payload_path(@payload.uuid)
    rescue Exception => error
      flash[:error] = error.message
      render :action => :edit
    end
  end





  ############################################################################
  private
  ############################################################################


  def seek_payload
    @payload = Payload.find_by_uuid!(params[:id])
  end

  def payload_params
    params.require(:payload).permit(:file, :descr, :uploaded_at)
  end


end

app/helpers/admin/payloads_helper.rb
module Admin::PayloadsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/externals_helper.rb
module ExternalsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/payloads_helper.rb
module PayloadsHelper
end

app/views/admin/payloads/action.html.erb
<%= form_for [:admin, @payload] do |form| %>
  <div class="form-group">
    <%= form.label :owner_email %>
    <%= form.text_field :owner_email, :class=>"form-control" %>
  </div>
  <%= form.hidden_field :user_id, :value => current_user.id %>
  <button type="submit" class="btn btn-primary">Submit</button>
<% end %>

app/views/admin/payloads/index.html.erb
<p>
  <%= link_to  "New Payload", new_admin_payload_path, :class => "btn btn-sm btn-primary shadow-sm" %>
</p>


<%= will_paginate @payloads %>

<table class="table">
  <thead>
    <tr>
      <th>id</th>
      <th>UUID</th>
      <th>owner</th>
      <th>Created</th>
      <th>Uploaded</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @payloads.each do |payload| %>
      <tr>
        <td><%= payload.id %></td>
        <td><%= payload.uuid %></td>
        <td><%= payload.owner_email %></td>
        <td><%= time_ago_in_words(payload.created_at) %></td> 
        <td><%= time_ago_in_words(payload.uploaded_at) if payload.complete?  %></td>
        <td><%= link_to("view", payload_path(payload.uuid)) if payload.complete? %></td>
        <td>
          <% if payload.complete? %>
            <%= link_to(payload.file.url, :target => "blank") do %>
               <i class="fas fa-download"></i>
            <% end %>
          <% end %>
       </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @payloads %>

app/views/admin/shared/_sidebar.html.erb
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

  <!-- Sidebar - Brand -->
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
    <%= render :partial => "shared/text_logo" %>
  </a>
  <!-- Divider -->
  <hr class="sidebar-divider my-0">

  <!-- Nav Item - Dashboard -->
  <li class="nav-item active">
    <a class="nav-link" href="/admin">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>Dashboard</span></a>
  </li>

  <li class="nav-item active">
    <a class="nav-link" href="/admin/users">
      <i class="fas fa-users"></i>
      <span>Users</span></a>
  </li>

  <li class="nav-item active">
    <a class="nav-link" href="/admin/payloads">
      <i class="fas fa-parachute-box"></i>
      <span>All Payloads</span></a>
  </li>

  <li class="nav-item active">
    <a class="nav-link" href="/admin/payloads/completed">
      <i class="fas fa-parachute-box"></i>
      <span>Payloads w/ data</span></a>
  </li>

</ul>
<!-- End of Sidebar -->

app/views/admin/users/action.html.erb
<%= form_for [:admin, @user] do |form| %>
  <div class="form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, :class=>"form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, :class=>"form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, :class=>"form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :pasword %>
    <%= form.password_field :password, :class=>"form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, :class=>"form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :admin_level, "Is Admin" %>
    <%= form.check_box :admin_level, :class=>"form-control", :checked_value => 1, :unchecked_value => 0 %>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
<% end %>

app/views/admin/users/index.html.erb
<p>
  <%= link_to  "New User", new_admin_user_path, :class => "btn btn-sm btn-primary shadow-sm" %>
</p>
<%= will_paginate @users %>

<table class="table">
  <thead>
    <tr>
      <th>id</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Access Level</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.access_level %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @users %>

app/views/admins/show.html.erb
<p>
  <%= link_to  "New User", new_admin_user_path, :class => "btn btn-sm btn-primary shadow-sm" %>
  <%= link_to  "New Payload", new_admin_payload_path, :class => "btn btn-sm btn-primary shadow-sm" %>
</p>


<ul>Current Status
  <li><%= link_to "#{User.count} users", admin_users_path %></li>
  <li><%= link_to "#{Payload.count} payloads", admin_payloads_path %></li>
  <li><%= link_to "#{Payload.completed.count} completed payloads", completed_admin_payloads_path %></li>
</ul>

app/views/externals/show.html.erb
<div class="row">
  <div class="col-lg-12 text-center">
    <h1 class="mt-5"><i class="fas fa-parachute-box"></i></h1>
    <p class="lead">this is payload.io</p>
    <p class="lead">give us your stuff</p>
  </div>
</div>

app/views/homes/show.html.erb
This page is just to illustrate that users that are NOT admins can have their own functaionlity apart from anon users or admins

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Payload</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "bootstrap.min.css" %>
  <%= stylesheet_link_tag "sb-admin-2.min.css" %>
  <%= stylesheet_link_tag "all.css" %>

  <!-- Custom fonts for this template-->
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">



  <%= csrf_meta_tags %>
  <%= yield :head %>
</head>
<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <%= render :partial => "admin/shared/sidebar" %>

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">


          <h1><%= controller_name %>: <%= action_name %></h1>
          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

     

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small"><%= current_user.name %></span>
              </a>
            </li>

            <div class="topbar-divider d-none d-sm-block"></div>
            <!-- Nav Item - Logout -->
            <li class="nav-item dropdown no-arrow mx-1">
              <%= link_to(destroy_user_session_path, :class => "nav-link", :method => :delete) do %>
                <i class="fas fa-sign-out-alt"></i>
                Logout
              <% end %>
            </li>

          </ul>

        </nav>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">
          <%= render :partial => "shared/flash_notifications" %>
          <%= yield %>
        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; Your Website 2019</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="login.html">Logout</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->

  <!-- Core plugin JavaScript-->
  <!-- <script src="vendor/jquery-easing/jquery.easing.min.js"></script> -->

  <!-- Custom scripts for all pages-->
  <%= javascript_include_tag "sb-admin-2.min.js" %>
  <%= javascript_include_tag "all.min.js" %>
<%#
  <!-- Page level plugins -->
  <script src="vendor/chart.js/Chart.min.js"></script>

  <!-- Page level custom scripts -->
  <script src="js/demo/chart-area-demo.js"></script>
  <script src="js/demo/chart-pie-demo.js"></script>
%>
</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Payload</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "bootstrap.min.css" %>
  <%= javascript_include_tag "bootstrap.min.js" %>
  <%= stylesheet_link_tag "all.css" %>
  <%= javascript_include_tag "all.min.js" %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
</head>
<body>
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container">
      <a class="navbar-brand" href="#">
        <%= render :partial => "shared/text_logo" %>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%= render :partial => "shared/topnav" %>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">
    <%= render :partial => "shared/flash_notifications" %>
    <%= yield %>
  </div>

</body>
</html>

app/views/payloads/edit.html.erb
<%= form_for :payload, url: {action: "update", params: {id: @payload.uuid}}, method: "patch" do |form| %>
  <div class="form-group">
    <%= form.label :file %>
    <%= form.file_field :file %>
  </div>
  <div class="form-group">
    <%= form.label :descr %>
    <%= form.text_area :descr, :class=>"form-control" %>
  </div>
  <%= form.hidden_field :uploaded_at, :value => Time.now %>
  <button type="submit" class="btn btn-primary">Submit</button>
<% end %>

app/views/payloads/show.html.erb
<dl class="row">
  <% @payload.attributes.each do |key, value| %>
    <dt class="col-sm-3"><%= key %></dt>
    <dd class="col-sm-9"><%= value %></dd>
  <% end %>
</dl>

app/views/shared/_flash_notifications.html.erb
<div class="notice"><%= notice %></div>
<div class="error" style="font-size: 1rem; width: 100%"><%= flash[:error] %></div>
<div class="success"><%= flash[:success] %></div>
<div class="alert"><%= alert %></div>

app/views/shared/_text_logo.html.erb
<div class="sidebar-brand-icon rotate-n-15">
  <i class="fas fa-parachute-box"></i>
</div>
<div class="sidebar-brand-text mx-3">Payloads.io</div>

app/views/shared/_topnav.html.erb
<div class="collapse navbar-collapse" id="navbarResponsive">
  <ul class="navbar-nav ml-auto">
    <li class="nav-item">
      <% if user_signed_in? %>
        <%= link_to('Logout', destroy_user_session_path, :class => "nav-link", :method => :delete) %>
      <% else %>
        <%= link_to('Login', new_user_session_path, :class => "nav-link") %>  
      <% end %>
    </li>
  </ul>
</div>